services:
  postgres:
    image: postgres:15.3-alpine
    container_name: akibastores-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: super-secure-password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: -E UTF8 --locale=C
    command: postgres -cshared_preload_libraries=pg_stat_statements
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - akibastores_network
    restart: unless-stopped

  medusa:
    build:
      context: ./medusa-marketplace-demo
      dockerfile: Dockerfile
    container_name: akibastores-medusa
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./medusa-marketplace-demo/.env.docker:/application/.env
    command: sh -c "npx medusa db:setup --db marketplace && yarn dev"
    networks:
      - akibastores_network
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://marketplace:super-secure-password@postgres:5432/marketplace
      - STORE_CORS=http://storefront:8000,http://localhost:8000
      - JWT_SECRET=supersecret
      - COOKIE_SECRET=supersecret
      - API_KEY=your-secure-admin-key-123

  storefront:
    build:
      context: ./medusa-storefront
      dockerfile: Dockerfile
    container_name: akibastores-storefront
    ports:
      - "8000:8000"
    environment:
      - MEDUSA_BACKEND_URL=http://medusa:9000 
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://medusa:9000
      - NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY:-pk_71d161680980d446caa673b7e54347dbaa28af1bb6920706bf9652eaee2f4ceb}
      - NEXT_PUBLIC_DEFAULT_REGION=us
    networks:
      - akibastores_network
    depends_on:
      - medusa
    volumes:
      - ./medusa-storefront:/app
      - /app/node_modules
    command: sh -c "npm run dev"

volumes:
  postgres_data:
    name: akibastores_postgres_data

networks:
  akibastores_network:
    name: akibastores_network