services:
  medusa:
    build:
      context: ./medusa-marketplace-demo
      dockerfile: Dockerfile
    container_name: akibastores-medusa
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./medusa-marketplace-demo/.env.docker:/application/.env
    command: sh -c "npx medusa db:setup --db marketplace && yarn dev"
    networks:
      - akibastores_network

networks:
  akibastores_network:
    external: true
    name: akibastores_network